# Generated by Django 5.0.6 on 2024-06-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='league_id',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
