# Generated by Django 5.0.6 on 2024-06-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_country_code_alter_country_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.URLField(blank=True, null=True),
        ),
    ]
