# Generated by Django 5.1.1 on 2024-10-02 16:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_news_new'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Article',
        ),
    ]
