# Generated by Django 5.1.1 on 2024-10-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_category_media_article_category_article_mainmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(default='mine is '),
        ),
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.URLField(default='pexels-luis-gomes-546819.jpg'),
        ),
    ]
