# Generated by Django 5.1.1 on 2024-10-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
